version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  postgres:
    image: postgres
    container_name: postgres-open-station
    environment:
      - POSTGRES_USER=dbUser
      - POSTGRES_PASSWORD=dbPassword
      - POSTGRES_DB=charges
    volumes:
      - ../stationsDb/temp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000" # Blob service
      - "10001:10001" # Queue service
      - "10002:10002" # Table service
    volumes:
      - ../stationsDb/temp/azurite:/data
    command: "azurite-blob --blobHost 0.0.0.0 --location /data"

volumes:
  esdata:
    driver: local
  mssqldata:
    driver: local